yaroslav
Bugaienko/TestGitTeam pull request #5
Opened 2024-02-27 20:03 UTC by YarkoHub

2024-02-27 20:13 UTC, IvannnnavI approved these changes

2024-02-27 20:17 UTC, SirenkoMaksym approved these changes

2024-02-27 20:32 UTC, Bugaienko requested changes
Название файла не соответсвует заданию

2024-02-27 20:35 UTC, Bugaienko approved these changes

2024-02-27 20:36 UTC, Bugaienko requested changes
Название файла не соответсвует заданию

2024-02-28 16:42 UTC, Bugaienko approved these changes

2024-02-28 16:46 UTC, merged